### ISSUE TITLE
More flexibility for when LogActivityComponent actually logs?

### ISSUE THREAD

**Issue by cutz** [OpenNTI/nti.zodb#11]
LogActivityComponent was updated to only log zodb activity based on a [`min_loads_and_stores`](https://github.com/NextThought/nti.zodb/blob/master/src/nti/zodb/activitylog.py#L121) threshold. This has greatly reduced the logging we see from this component. However, with a threshold of 1, we still seeing this activity logging account for nearly 15% of our log traffic in a 24 hour period (1.94M activity logs written).  Looking at the distribution of loads and stores the majority logged have a `loads + stores` that are < 10 (1.1M record). (edit: note the scale on the graph is logarithmic)

![Screen Shot 2021-04-01 at 9 49 36 AM](https://user-images.githubusercontent.com/2072268/113312138-94f67f00-92cf-11eb-85b1-9fe4073b9e41.png) 

However, I wonder if it makes sense to have separate thresholds for loads and stores. We typically use this logging to identify requests that made a massive number of db loads, or requests that store data unexpectedly. Does it make sense to have different thresholds and set loads to something like 20 and stores to 1, or should we just bump the existing combined threshold up a bit (to 10) to reduce logging?

**Comment by jamadden** [comment]
Why not do both: separate thresholds, plus a combined threshold. `if loads > load_t or stores > store_t or loads + stores > activity_t:`; that way we can express "if there are a bunch of loads, or a bunch of stores, or just a bunch of activity, report it". We could use something like 10 for all three values, so we'd log for 9 loads and 1 store, or 10 loads and 0 stores.

I can have a PR soon.

**Comment by cutz** [comment]
That sounds like a good solution to me. @jzuech3  you good with those thresholds? Is it worth pulling those from the environment or driving those via config?

**Comment by jamadden** [comment]
I was planning to be able to read from the environment to override the defaults.
